/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    jacoco
    id("org.sonarqube") version "5.0.0.4638"
}

allprojects {
    version = "1.0.0"
    repositories {
        // Use Maven Central for resolving dependencies.
        mavenCentral()
    }
}


// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sonar {
    properties {
        property("sonar.projectKey", "nikfarjam_gradle-multimodule")
        property("sonar.projectName", "gradle-multimodule")
        property("sonar.organization", "gradle-multimodule") 
        property("sonar.host.url", "https://sonarcloud.io")

    }
}
