/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mehdi

class CollectionUtils {
    fun <T> merge(list1: List<T>, list2: List<T>): List<T> {
        return  buildList() {
            addAll(list1)
            addAll(list2)
        }
    }

    fun <T> retainAll(list1: List<T>, list2: List<T>): List<T> {
        return list1.retainAll(list2)
    }
}
