/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mehdi

import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertFalse

class StringUtilsTest {
    @Test fun isEmptyReturnsTrue() {
        val classUnderTest = StringUtils()
        assertTrue(classUnderTest.isEmpty(""), "isEmpty('') should return 'true'")
        assertTrue(classUnderTest.isEmpty("   "), "isEmpty('  ') should return 'true'")
    }

    @Test fun isEmptyReturnsFalse() {
        val classUnderTest = StringUtils()
        assertFalse(classUnderTest.isEmpty("test"), "isEmpty('test') should return 'false'")
    }
}
