/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mehdi

import kotlin.test.Test
import kotlin.test.assertEquals

class CollectionUtilsTest {
    @Test fun mergeListOfStrings() {
        val classUnderTest = CollectionUtils()
        val list1 = listOf<String>("a", "b")
        val list2 = listOf<String>("c")

        val actual = classUnderTest.merge(list1, list2)

        assertEquals(actual, listOf<String>("a", "b", "c"),
         "merge(['a', 'b'], ['c']) should return ['a', 'b', 'c']")
    }
}
